name: Apk Builder CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build apk
    runs-on: ubuntu-latest
    steps:
      - name: Cancel previous runs
        uses: styfle/cancel-workflow-action@0.5.0
        with:
          access_token: ${{ github.token }}

      - uses: actions/checkout@v2

      - name: set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build apk
        uses: eskatos/gradle-command-action@v1
        with:
          arguments: assembleDebug
      - name: Upload app-debug.apk and output-metadata.json
        uses: actions/upload-artifact@v2
        with:
          name: apk-build
          path: app/build/outputs/apk/debug/
