name: Format

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  formatting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: axel-op/googlejavaformat-action@v3
        with:
          args: "--skip-sorting-imports --replace"
          githubToken: ${{ secrets.TOKEN }}
